version: '3.8'

services:
  api:
    build:
        context: ./../
        dockerfile: Dockerfile
    env_file: .env
    container_name: sample_api
    ports:
      - 5069:80
      - 5070:443
    depends_on:
      - mongo
      - redis
    volumes:
      - .\\certificates\:/https:ro
    networks:
      - front-tier
      - back-tier
  
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=no
    volumes:
      - ${MONGO_HOST_DATA}/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - back-tier

  redis:
    container_name: redis
    image: redis:6-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - back-tier

volumes:
    db:
        driver: local
    api:
        driver: local
    mongo:
        driver: local

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
