version: '3.8'

services:
  api:
    build:
        context: ./../
        dockerfile: Dockerfile
    env_file: .env
    container_name: sample_api
    ports:
      - 8081:80
    depends_on:
      - mongo
      - redis
  
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - AUTH=no
    volumes:
      - ${MONGO_HOST_DATA}/db:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:6-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
    db:
      driver: local