apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-mongo-pv
  labels:
    app: sample
    env: dev
    targetApp: mongo
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongo-pv