apiVersion: v1
kind: PersistentVolume
metadata:
  name: sample-redis-pv
  labels:
    app: sample
    env: dev
    targetApp: redis
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis-pv